# Generated by Django 5.2.5 on 2025-09-04 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
        ("realtime_engine", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GELimitEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_bought",
                    models.IntegerField(
                        default=0, help_text="Quantity bought in current 4-hour period"
                    ),
                ),
                (
                    "max_limit",
                    models.IntegerField(help_text="Maximum buy limit for this item"),
                ),
                ("last_purchase_time", models.DateTimeField(auto_now_add=True)),
                (
                    "limit_reset_time",
                    models.DateTimeField(
                        help_text="When the limit resets (4 hours from first purchase)"
                    ),
                ),
                (
                    "average_purchase_price",
                    models.IntegerField(
                        blank=True, help_text="Average price paid", null=True
                    ),
                ),
                (
                    "total_investment",
                    models.IntegerField(default=0, help_text="Total GP invested"),
                ),
                ("is_limit_reached", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limit_entries",
                        to="items.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ge_limits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ge_limit_entries",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="ge_limit_en_user_id_37f7cd_idx",
                    ),
                    models.Index(
                        fields=["limit_reset_time"],
                        name="ge_limit_en_limit_r_6b5150_idx",
                    ),
                    models.Index(
                        fields=["is_limit_reached"],
                        name="ge_limit_en_is_limi_00d25e_idx",
                    ),
                ],
                "unique_together": {("user", "item")},
            },
        ),
    ]
