# Generated by Django 5.2.5 on 2025-09-04 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
        ("realtime_engine", "0003_sentimentanalysis_itemsentiment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prediction_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "current_price",
                    models.FloatField(help_text="Price at time of prediction"),
                ),
                (
                    "predicted_price_1h",
                    models.FloatField(help_text="Predicted price in 1 hour"),
                ),
                (
                    "predicted_price_4h",
                    models.FloatField(help_text="Predicted price in 4 hours"),
                ),
                (
                    "predicted_price_24h",
                    models.FloatField(help_text="Predicted price in 24 hours"),
                ),
                (
                    "confidence_1h",
                    models.FloatField(
                        default=0.5, help_text="Prediction confidence (0-1)"
                    ),
                ),
                (
                    "confidence_4h",
                    models.FloatField(
                        default=0.5, help_text="Prediction confidence (0-1)"
                    ),
                ),
                (
                    "confidence_24h",
                    models.FloatField(
                        default=0.5, help_text="Prediction confidence (0-1)"
                    ),
                ),
                (
                    "trend_direction",
                    models.CharField(
                        choices=[
                            ("bullish", "Bullish"),
                            ("bearish", "Bearish"),
                            ("neutral", "Neutral"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                (
                    "prediction_factors",
                    models.JSONField(
                        default=dict, help_text="Factors used in prediction"
                    ),
                ),
                (
                    "model_version",
                    models.CharField(default="statistical_v1", max_length=50),
                ),
                (
                    "prediction_method",
                    models.CharField(default="statistical_ensemble", max_length=100),
                ),
                ("actual_price_1h", models.FloatField(blank=True, null=True)),
                ("actual_price_4h", models.FloatField(blank=True, null=True)),
                ("actual_price_24h", models.FloatField(blank=True, null=True)),
                (
                    "error_1h",
                    models.FloatField(
                        blank=True, help_text="Prediction error percentage", null=True
                    ),
                ),
                (
                    "error_4h",
                    models.FloatField(
                        blank=True, help_text="Prediction error percentage", null=True
                    ),
                ),
                (
                    "error_24h",
                    models.FloatField(
                        blank=True, help_text="Prediction error percentage", null=True
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_predictions",
                        to="items.item",
                    ),
                ),
            ],
            options={
                "db_table": "price_predictions",
                "ordering": ["-prediction_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["item", "-prediction_timestamp"],
                        name="price_predi_item_id_34a3f4_idx",
                    ),
                    models.Index(
                        fields=["-confidence_24h"],
                        name="price_predi_confide_80d965_idx",
                    ),
                    models.Index(
                        fields=["trend_direction"],
                        name="price_predi_trend_d_dd8192_idx",
                    ),
                    models.Index(
                        fields=["-prediction_timestamp"],
                        name="price_predi_predict_d5578e_idx",
                    ),
                ],
            },
        ),
    ]
