# Generated by Django 5.2.5 on 2025-08-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_startup_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When Django backend was last started",
                    ),
                ),
                (
                    "previous_shutdown_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When Django backend was previously shut down",
                        null=True,
                    ),
                ),
                (
                    "startup_count",
                    models.IntegerField(
                        default=1, help_text="Number of times system has started"
                    ),
                ),
                (
                    "last_full_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="When last complete data sync was performed",
                        null=True,
                    ),
                ),
                (
                    "last_price_sync",
                    models.DateTimeField(
                        blank=True, help_text="When prices were last synced", null=True
                    ),
                ),
                (
                    "last_item_mapping_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="When item mapping was last synced",
                        null=True,
                    ),
                ),
                (
                    "last_embedding_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="When embeddings were last updated",
                        null=True,
                    ),
                ),
                (
                    "total_items_count",
                    models.IntegerField(
                        default=0, help_text="Total OSRS items in database"
                    ),
                ),
                (
                    "profitable_items_count",
                    models.IntegerField(
                        default=0, help_text="Currently profitable items"
                    ),
                ),
                (
                    "new_items_discovered",
                    models.IntegerField(
                        default=0, help_text="New items found in last sync"
                    ),
                ),
                (
                    "data_quality_score",
                    models.FloatField(
                        default=0.0, help_text="Overall data quality score (0-100)"
                    ),
                ),
                (
                    "embedding_index_status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("rebuilding", "Rebuilding"),
                            ("corrupted", "Corrupted"),
                            ("missing", "Missing"),
                        ],
                        default="missing",
                        max_length=20,
                    ),
                ),
                (
                    "current_sync_strategy",
                    models.CharField(
                        choices=[
                            ("quick_volume", "Quick Volume Sync"),
                            ("full_price", "Full Price Sync"),
                            ("full_refresh", "Full Data Refresh"),
                            ("complete_rebuild", "Complete Rebuild"),
                            ("none", "No Sync Needed"),
                        ],
                        default="none",
                        max_length=50,
                    ),
                ),
                ("sync_in_progress", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System State",
                "verbose_name_plural": "System States",
                "db_table": "system_state",
            },
        ),
        migrations.CreateModel(
            name="SyncOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("startup_sync", "Startup Sync"),
                            ("quick_volume", "Quick Volume Sync"),
                            ("full_price", "Full Price Sync"),
                            ("full_refresh", "Full Data Refresh"),
                            ("complete_rebuild", "Complete Rebuild"),
                            ("item_mapping", "Item Mapping Sync"),
                            ("embeddings", "Embeddings Sync"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("items_processed", models.IntegerField(default=0)),
                ("items_created", models.IntegerField(default=0)),
                ("items_updated", models.IntegerField(default=0)),
                ("errors_encountered", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "sync_operations",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["operation_type", "-started_at"],
                        name="sync_operat_operati_4ca1f2_idx",
                    ),
                    models.Index(
                        fields=["status"], name="sync_operat_status_c4589b_idx"
                    ),
                ],
            },
        ),
    ]
