# Generated by Django 5.2.5 on 2025-09-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_strategies", "0002_alter_tradingstrategy_strategy_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="decantingopportunity",
            name="profit_per_hour",
            field=models.IntegerField(default=0, help_text="Estimated profit per hour"),
        ),
    ]
