# Generated by Django 5.2.5 on 2025-09-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_strategies", "0003_decantingopportunity_profit_per_hour"),
    ]

    operations = [
        migrations.AddField(
            model_name="decantingopportunity",
            name="confidence_score",
            field=models.FloatField(
                default=0.0,
                help_text="Overall confidence score based on price and volume analysis",
            ),
        ),
        migrations.AddField(
            model_name="decantingopportunity",
            name="liquidity_score",
            field=models.FloatField(
                default=0.0,
                help_text="Liquidity score from 0.0-1.0 based on volume consistency",
            ),
        ),
        migrations.AddField(
            model_name="decantingopportunity",
            name="trading_activity",
            field=models.CharField(
                choices=[
                    ("very_active", "Very Active"),
                    ("active", "Active"),
                    ("moderate", "Moderate"),
                    ("low", "Low"),
                    ("inactive", "Inactive"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="Trading activity level based on volume analysis",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="decantingopportunity",
            name="volume_analysis_data",
            field=models.JSONField(
                blank=True,
                help_text="Full volume analysis data from RuneScape Wiki API",
                null=True,
            ),
        ),
    ]
