# Generated by Django 5.2.5 on 2025-09-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trading_strategies", "0004_decantingopportunity_confidence_score_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="setcombiningopportunity",
            unique_together={("set_name",)},
        ),
    ]
