# Generated by Django 5.2.5 on 2025-08-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
        ("prices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricesnapshot",
            name="data_interval",
            field=models.CharField(
                default="latest",
                help_text="Data interval (latest, 5m, 1h)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pricesnapshot",
            name="high_price_volume",
            field=models.IntegerField(
                blank=True, help_text="Number of high price transactions", null=True
            ),
        ),
        migrations.AddField(
            model_name="pricesnapshot",
            name="low_price_volume",
            field=models.IntegerField(
                blank=True, help_text="Number of low price transactions", null=True
            ),
        ),
        migrations.AddField(
            model_name="pricesnapshot",
            name="price_change_pct",
            field=models.FloatField(
                blank=True, help_text="Price change % from previous snapshot", null=True
            ),
        ),
        migrations.AddField(
            model_name="pricesnapshot",
            name="price_volatility",
            field=models.FloatField(
                blank=True, help_text="Price volatility score (0-1)", null=True
            ),
        ),
        migrations.AddField(
            model_name="pricesnapshot",
            name="total_volume",
            field=models.IntegerField(
                blank=True, help_text="Total trading volume in time period", null=True
            ),
        ),
        migrations.AddField(
            model_name="profitcalculation",
            name="five_min_volume",
            field=models.IntegerField(default=0, help_text="5min trading volume"),
        ),
        migrations.AddField(
            model_name="profitcalculation",
            name="hourly_volume",
            field=models.IntegerField(default=0, help_text="1h trading volume"),
        ),
        migrations.AddField(
            model_name="profitcalculation",
            name="price_momentum",
            field=models.FloatField(default=0.0, help_text="Price momentum indicator"),
        ),
        migrations.AddField(
            model_name="profitcalculation",
            name="price_volatility",
            field=models.FloatField(
                default=0.0, help_text="Price volatility score (0-1)"
            ),
        ),
        migrations.AddField(
            model_name="profitcalculation",
            name="volume_category",
            field=models.CharField(
                choices=[
                    ("hot", "Hot - High volume"),
                    ("warm", "Warm - Medium volume"),
                    ("cool", "Cool - Low volume"),
                    ("cold", "Cold - Very low volume"),
                    ("inactive", "Inactive"),
                ],
                default="inactive",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profitcalculation",
            name="volume_weighted_score",
            field=models.IntegerField(
                default=0, help_text="Volume-weighted recommendation score"
            ),
        ),
        migrations.AddIndex(
            model_name="pricesnapshot",
            index=models.Index(
                fields=["total_volume"], name="price_snaps_total_v_eb3487_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricesnapshot",
            index=models.Index(
                fields=["data_interval"], name="price_snaps_data_in_cd8744_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricesnapshot",
            index=models.Index(
                fields=["price_volatility"], name="price_snaps_price_v_53e028_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricesnapshot",
            index=models.Index(
                fields=["item", "data_interval", "-created_at"],
                name="price_snaps_item_id_c7d770_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="profitcalculation",
            index=models.Index(
                fields=["-volume_weighted_score"], name="profit_calc_volume__9847d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profitcalculation",
            index=models.Index(
                fields=["volume_category"], name="profit_calc_volume__6385d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profitcalculation",
            index=models.Index(
                fields=["daily_volume"], name="profit_calc_daily_v_619a52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profitcalculation",
            index=models.Index(
                fields=["price_volatility"], name="profit_calc_price_v_defe96_idx"
            ),
        ),
    ]
