# Generated by Django 5.2.5 on 2025-08-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
        ("prices", "0002_add_volume_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="profitcalculation",
            name="confidence_score",
            field=models.FloatField(
                default=0.5, help_text="Confidence in data accuracy (0.0-1.0)"
            ),
        ),
        migrations.AddField(
            model_name="profitcalculation",
            name="data_age_hours",
            field=models.FloatField(
                default=0.0, help_text="Age of source data in hours"
            ),
        ),
        migrations.AddField(
            model_name="profitcalculation",
            name="data_quality",
            field=models.CharField(
                default="unknown",
                help_text="Data quality level (fresh, recent, acceptable, stale)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profitcalculation",
            name="data_source",
            field=models.CharField(
                default="unknown",
                help_text="Source of price data (weird_gloop, wiki_timeseries_5m, etc.)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="profitcalculation",
            name="source_timestamp",
            field=models.DateTimeField(
                blank=True,
                help_text="When source data was originally created",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="profitcalculation",
            index=models.Index(
                fields=["data_source"], name="profit_calc_data_so_d924ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profitcalculation",
            index=models.Index(
                fields=["data_quality"], name="profit_calc_data_qu_8a3694_idx"
            ),
        ),
    ]
