# Generated by Django 5.2.5 on 2025-09-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
        ("prices", "0005_historicalanalysis_historicalprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="profitcalculation",
            name="alch_efficiency_rating",
            field=models.IntegerField(
                default=0, help_text="Alch efficiency based on profit-per-time (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="profitcalculation",
            name="high_alch_viability_score",
            field=models.IntegerField(
                default=0, help_text="High alchemy viability score (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="profitcalculation",
            name="magic_xp_efficiency",
            field=models.FloatField(
                default=0.0, help_text="Magic XP per GP spent efficiency"
            ),
        ),
        migrations.AddField(
            model_name="profitcalculation",
            name="sustainable_alch_potential",
            field=models.IntegerField(
                default=0,
                help_text="Sustainable alching potential considering buy limits (0-100)",
            ),
        ),
        migrations.AddIndex(
            model_name="profitcalculation",
            index=models.Index(
                fields=["-high_alch_viability_score"],
                name="profit_calc_high_al_fcb1c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="profitcalculation",
            index=models.Index(
                fields=["-alch_efficiency_rating"],
                name="profit_calc_alch_ef_a5a8f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="profitcalculation",
            index=models.Index(
                fields=["-sustainable_alch_potential"],
                name="profit_calc_sustain_6e5425_idx",
            ),
        ),
    ]
